config/routes.rb
Crowdreplay::Application.routes.draw do

  # Session Routes
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users, :except => [:index,:show,:destroy,:edit] do
    collection do
      get :edit
    end
  end
  
  # CRUD Resources
  resources :recorders, :except => [:show] do
    member do
      get :start
      get :stop
    end
    
    collection do
      get :auth_redirect
    end
  end
  
  resources :events
  
  # Game View
  get 'game_view/show'
  post 'game_view/show'
  get 'game_view/realtime'
  get 'game_view/data'
  get 'game_view/tweets_at_time'
  
  # Authentication URLs for Omniauth
  match '/auth/:provider/callback' => 'recorders#auth_redirect'
  
  # Map the root
  root :to => 'game_view#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :tweet_categories
  attr_accessible :name, :start_time, :end_time, :realtime
  
  def add_categories(category_names)
    category_names = category_names.split(",")
    category_names.each { |category_name| 
    
      category = TweetCategory.find_by_category(category_name)
      if category and !self.tweet_categories.include?(category)
        self.tweet_categories << category
      end
    }
  end
  
  def link_hash
    if self.realtime
      if self.start_time
        {:controller => :game_view, :action => :realtime, :categories => self.category_names, :starttime => self.start_time}
      else
        {:controller => :game_view, :action => :realtime, :categories => self.category_names}
      end
    else
      if self.start_time and self.end_time
        {:controller => :game_view, :action => :show, :categories => self.category_names, :starttime => self.start_time, :endtime => self.end_time}
      elsif self.start_time
        {:controller => :game_view, :action => :show, :categories => self.category_names, :starttime => self.start_time}
      else
        {:controller => :game_view, :action => :show, :categories => self.category_names}
      end
    end
  end
  
  def category_names
    str = self.tweet_categories[0].category
    if self.tweet_categories.length > 1
      self.tweet_categories[1..(self.tweet_categories.length-1)].each { |c| 
        str += "," + c.category
      }
    end
    str
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_admin, :except => [:index,:show]
  
  # GET /events
  # GET /events.xml
  def index
    @events = Event.find(:all, :order => :start_time)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new
    @categories = @event.tweet_categories

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])
    
    respond_to do |format|
      if @event.save
        @event.add_categories(params[:categories])
        
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(root_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<%= render "shared/error_messages", :target => @event %>

		<%= form_for @event do |f| %>

			<div class="control-group">
		    	<%= f.label :name, :class => 'control-label' %><br />
		    	<%= f.text_field :name, :class => 'form-control' %>
			</div>

			<div class="control-group">
			    <%= label_tag :categories, :class => 'control-label' %><br />
			    <%= text_field_tag :categories, :class => 'form-control' %>
			</div>

			<div class="control-group">
			    <%= f.label :start_time, :class => 'control-label' %><br />
			    <%= f.datetime_select :start_time, :class => 'form-control' %>
			</div>

			<div class="control-group">
			    <%= f.label :end_time, :class => 'control-label' %><br />
			    <%= f.datetime_select :end_time, :class => 'form-control' %>
			</div>

			<div class="control-group">
				<%= f.label :realtime do %>
					<%= f.check_box :realtime %> 
					Realtime
				<% end -%>
			</div>
		
			<div class="form-actions">
		    	<%= f.submit nil, :class => 'btn btn-primary' %>
			</div>
		<% end -%>
	</div>
</div>

app/views/events/edit.html.erb
<div class="page-header">
  <h2>Edit <%= @event.name %></h2>
</div>

<%= render :partial => 'form' %>

app/views/events/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Start time</th>
    <th>End time</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= link_to event.name, {:controller => :game_view, :action => :show, :eventid => event.id} %></td>
    <td><%=h TweetCategory.find_by_id(event.category_id).category %></td>
    <td><%=h event.start_time %></td>
    <td><%=h event.end_time %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/events/new.html.erb
<div class="page-header">
	<h2>New event</h2>
</div>

<%= render :partial => 'form' %>

app/views/events/show.html.erb
<p>
  <b>Event Name:</b>
  <%=h @event.name %>
</p>

<p>
  <b>Categories:</b>
  <%=h concat_categories(@event.tweet_categories) %>
</p>

<% if !@event.realtime -%>
<p>
  <b>Start time:</b>
  <%=h @event.start_time.strftime("%b %d, %Y  %k:%M %Z") %>
</p>

<p>
  <b>End time:</b>
  <%=h @event.end_time.strftime("%b %d, %Y  %k:%M %Z") %>
</p>
<% else -%>
<p>
	<i>Realtime Event</i>
</p>
<% end -%>

<% if current_user and current_user.admin? -%>
	<%= link_to 'Edit', edit_event_path(@event) %>
<% end -%>