config/routes.rb
Crowdreplay::Application.routes.draw do

  # Session Routes
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users, :except => [:index,:show,:destroy,:edit] do
    collection do
      get :edit
    end
  end
  
  # CRUD Resources
  resources :recorders, :except => [:show] do
    member do
      get :start
      get :stop
    end
    
    collection do
      get :auth_redirect
    end
  end
  
  resources :events
  
  # Game View
  get 'game_view/show'
  post 'game_view/show'
  get 'game_view/realtime'
  get 'game_view/data'
  get 'game_view/tweets_at_time'
  
  # Authentication URLs for Omniauth
  match '/auth/:provider/callback' => 'recorders#auth_redirect'
  
  # Map the root
  root :to => 'game_view#index'
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default root_url
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<%- model_class = UserSession -%>
<div class="page-header">
  <h1>Welcome back!</h1>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<p>
			If you don't have an account yet, <%= link_to "register for one here.", new_user_path %>
		</p>
		
		<%= form_for @user_session, :as => :user_session, :url => { :action => "create" } do |f| %>
			<%= render "shared/error_messages", :target => @user_session %>

			<div class="form-group spaced">
				<%= f.label :email %>
				<%= f.text_field :email, :class => 'form-control', :type => :email %>
			</div>

			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, :class => 'form-control' %>
			</div>

			<div class="checkbox">
				<%= f.label :remember_me do %>
					<%= f.check_box :remember_me %> 
					Remember Me
				<% end -%>
			</div>

			<div class="form-actions">
				<%= f.submit "Login", :class => 'btn btn-primary' %>
			</div>
		<% end %>
	</div>
</div>