config/routes.rb
Crowdreplay::Application.routes.draw do

  # Session Routes
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users, :except => [:index,:show,:destroy,:edit] do
    collection do
      get :edit
    end
  end
  
  # CRUD Resources
  resources :recorders, :except => [:show] do
    member do
      get :start
      get :stop
    end
    
    collection do
      get :auth_redirect
    end
  end
  
  resources :events
  
  # Game View
  get 'game_view/show'
  post 'game_view/show'
  get 'game_view/realtime'
  get 'game_view/data'
  get 'game_view/tweets_at_time'
  
  # Authentication URLs for Omniauth
  match '/auth/:provider/callback' => 'recorders#auth_redirect'
  
  # Map the root
  root :to => 'game_view#index'
end

app/models/recorder.rb
class Recorder < ActiveRecord::Base
  attr_accessible :category, :oauth_access_secret, :oauth_access_token, :query, :running, :status, :screen_name
  
  def set_screenname
    if (self.screen_name == nil or self.screen_name == "") and self.oauth_access_token != nil and self.oauth_access_secret != nil
      twitter = Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV['TWITTER_CONSUMER_KEY']
        config.consumer_secret     = ENV['TWITTER_CONSUMER_SECRET']
        config.access_token        = self.oauth_access_token
        config.access_token_secret = self.oauth_access_secret
      end
    
      self.screen_name = twitter.user.screen_name
    end
  end
end

app/controllers/recorders_controller.rb
class RecordersController < ApplicationController
  before_filter :require_admin

  # GET /recorders
  # GET /recorders.json
  def index
    @recorders = Recorder.all
  end

  # GET /recorders/new
  # GET /recorders/new.json
  def new
    if session[:recorder] and session[:recorder].id == nil
      @recorder = session[:recorder]
      session[:recorder] = nil
    else
      @recorder = Recorder.new
      session[:recorder] = nil
    end

    process_auth_tokens(session)
  end

  # GET /recorders/1/edit
  def edit
    if session[:recorder] and session[:recorder].id != nil
      @recorder = session[:recorder]
      session[:recorder] = nil
    else
      @recorder = Recorder.find(params[:id])
      session[:recorder] = nil
    end
    
    process_auth_tokens(session)
    
    session[:recorder_state] = "edit"
    session[:auth_redirect] = url_for edit_recorder_path(@recorder)
  end

  def auth_redirect
    auth = request.env["omniauth.auth"]
    session[:access_token] = auth['credentials'].token
    session[:access_secret] = auth['credentials'].secret
    
    redirect_to session[:auth_redirect]
  end

  # POST /recorders
  # POST /recorders.json
  def create
    @recorder = Recorder.new(params[:recorder])
    @recorder.status = "Stopped"
    @recorder.running = false

    if params[:commit] == "Select Twitter Account"
      session[:recorder] = @recorder
      session[:auth_redirect] = new_recorder_path
      
      redirect_to '/auth/twitter'
    else
      if @recorder.save
        redirect_to recorders_path
      else
        render :action => "new"
      end
    end
  end

  # PUT /recorders/1
  # PUT /recorders/1.json
  def update
    @recorder = Recorder.find(params[:id])
    @recorder.assign_attributes(params[:recorder])
    
    if params[:commit] == "Select Twitter Account"
      session[:recorder] = @recorder
      session[:auth_redirect] = edit_recorder_path(@recorder)
    
      redirect_to '/auth/twitter'
    else
      if @recorder.save
        redirect_to recorders_path
      else
        render :action => "edit"
      end
    end
  end

  # DELETE /recorders/1
  # DELETE /recorders/1.json
  def destroy
    @recorder = Recorder.find(params[:id])
    @recorder.destroy

    respond_to do |format|
      format.html { redirect_to recorders_url }
      format.json { head :no_content }
    end
  end
  
  def start
    @recorder = Recorder.find(params[:id])
    
    if @recorder.status == "Stopped" or @recorder.status == "Stopping"
      @recorder.status = "Starting"
      @recorder.save
    end
    
    redirect_to recorders_path
  end
  
  def stop
    @recorder = Recorder.find(params[:id])
    
    if @recorder.status == "Starting" or @recorder.status == "Running"
      @recorder.status = "Stopping"
      @recorder.save
    end
    
    redirect_to recorders_path
  end
  
  private
  
  def process_auth_tokens(session)
    if session[:access_token] and session[:access_secret]
      @recorder.oauth_access_token = session[:access_token]
      @recorder.oauth_access_secret = session[:access_secret]
      @recorder.set_screenname
      
      session[:access_token] = nil
      session[:access_secret] = nil
    end
  end
end

app/helpers/recorders_helper.rb
module RecordersHelper
end

app/views/recorders/_form.html.erb
<%= form_for(@recorder) do |f| %>
  <% if @recorder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recorder.errors.count, "error") %> prohibited this recorder from being saved:</h2>

      <ul>
      <% @recorder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :oauth_access_token %>
  <%= f.hidden_field :oauth_access_secret %>
  <%= f.hidden_field :screen_name %>

  <div class="form-group">
    <%= f.label "Name", :class => 'control-label' %><br />
    <%= f.text_field :category, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :query, :class => 'control-label' %><br />
    <%= f.text_field :query, :class => 'form-control' %>
  </div>
  <div class="form-group">
	<% if @recorder.screen_name %>
		<b>Twitter Account</b>: <%= @recorder.screen_name %> &nbsp;&nbsp;
	<% end -%>
	<%= f.submit 'Select Twitter Account', :class => 'btn btn-mini btn-warning' %>
  </div>

  <% if @recorder.status %>
	<div class="form-group">
	  <b>Status:</b> <%= @recorder.status %>
	</div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit :class => 'btn btn-mini btn-primary' %>
  </div>

<% end %>

app/views/recorders/edit.html.erb
<%= render 'form' %>

app/views/recorders/index.html.erb
<script>
	function refreshRecorders() {
		document.location.reload();
	}
	
	function initRefresh() {
		setInterval(refreshRecorders, 30000);
	}
	
	$(initRefresh);
</script>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Query</th>
      <th>Account</th>
      <th>Status</th>
	  <th></th>
	  <th></th>
    </tr>
  </thead>

<% @recorders.each do |recorder| %>
  <tr>
    <td style="vertical-align: middle;"><%= recorder.category %></td>
    <td style="vertical-align: middle;"><%= recorder.query %></td>
    <td style="vertical-align: middle;"><%= recorder.screen_name %></td>
    <td style="vertical-align: middle;"><%= recorder.status %></td>
	<td style="vertical-align: middle;">
		<% if recorder.running -%>
			<%= link_to 'View Data', :controller => "game_view", :action => "realtime", :categories => recorder.category %>
		<% end -%>
	</td>
	<td class="text-right">
	    <%= link_to 'Edit', edit_recorder_path(recorder), :class => 'btn btn-mini' %>
        <% if recorder.running or recorder.status == "Starting" -%>
			<%= link_to 'Stop', stop_recorder_path(recorder), :class => 'btn btn-mini btn-danger' %>
		<% else -%>
			<%= link_to 'Start', start_recorder_path(recorder), :class => 'btn btn-mini btn-success' %>
			<%= link_to 'Delete',
	                    recorder_path(recorder),
	                    :method => :delete,
	                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	                    :class => 'btn btn-mini btn-danger' %>
		<% end -%>
	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recorder', new_recorder_path, :class => 'btn btn-primary' %>

app/views/recorders/new.html.erb
<h2>New recorder</h2>

<%= render 'form' %>