config/routes.rb
Crowdreplay::Application.routes.draw do

  # Session Routes
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users, :except => [:index,:show,:destroy,:edit] do
    collection do
      get :edit
    end
  end
  
  # CRUD Resources
  resources :recorders, :except => [:show] do
    member do
      get :start
      get :stop
    end
    
    collection do
      get :auth_redirect
    end
  end
  
  resources :events
  
  # Game View
  get 'game_view/show'
  post 'game_view/show'
  get 'game_view/realtime'
  get 'game_view/data'
  get 'game_view/tweets_at_time'
  
  # Authentication URLs for Omniauth
  match '/auth/:provider/callback' => 'recorders#auth_redirect'
  
  # Map the root
  root :to => 'game_view#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdReplay</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:url" content="http://crowdreplay.com/"/>
  <meta property="og:title" content="CrowdReplay"/>
  <meta property="og:description" content="Using the social media crowd to help your sports viewing experience."/>
</head>
<body>

	<div class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header">
	      		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
				</button>
	      	</div>
	      	<div class="collapse navbar-collapse" id="navbar-collapse">
				<ul class="nav navbar-nav">
					<li><%= link_to "CrowdReplay", root_path %></li>
				</ul>
		        <ul class="nav navbar-nav pull-right">
					<% if current_user != nil -%>
						<% if current_user.admin? -%>
							<li><%= link_to "Recorders", recorders_path %></li>
						<% end -%>
						<li><%= link_to "Logout", logout_path %></li>
					<% elsif current_user == nil -%>
						<li><%= link_to "Login", login_path %></li>
				    <% end -%>
				</ul>
	      	</div>
	    </div>
	</div>    

	<div class="container">
		<%= yield %>
	</div>

	<div class="footer" id="footer">
		<div class="footer-content container">
			<div class="col-md-6">
				<p><small>Copyright &copy; 2014, Snooty Bird, LLC</small></p>
			</div>
			<div class="col-md-6 text-right">
				<p><small>For questions and information, please contact <a href="mailto:jeff@jeffreynichols.com">Jeff</a>.</small></p>
			</div>
		</div>
	</div>
	
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-51633029-2', 'crowdreplay.com');
	  ga('send', 'pageview');

	</script>
</body>
</html>